name: Playwright Tests
on:
  push:
    branches: [ main ]
jobs:
  playwrighttests:
    runs-on: windows-latest
    container:
      image: mcr.microsoft.com/playwright:v1.46.0-focal
      env:
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: Actions/checkout@v2
      - name: Run tests
        run: |
         echo "start the shopping store application"
         ./shopping-store-windows-386 &
         echo "Install dependencies from lockfile"
         npm ci
         echo "Run Playwright tests"
         npm run test:ci